- name: Install packages using loops
  hosts: all
  tasks:
   - name: Install packages
     ansible.builtin.package:
      name: "{{ item }}"
      state: present
     #ansible.builtin.debug: 
      #msg: "Installing {{ item }} package"
     loop:

      - mysql
      - nginx
      - maven   