- name: Install packages using loops
  hosts: localhost
  connection: local
  become: yes
  tasks:
   - name: Install packages
     ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
     #ansible.builtin.debug: 
      #msg: "Installing {{ item }} package"
     loop:

      - { name: "ant" , state: "present" }
      - { name: "nginx" , state: "absent" }
      - { name: "maven" , state: "absent" }